<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CloudinaryDotNet" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Ardalis.Specification.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.AspNetCore.Http" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="Moq" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Shared.Application\Shared.Application.csproj" />
	</ItemGroup>

</Project>
