<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Shared.Domain\Shared.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Shared.Infrastructure\Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\OrderService.Application\OrderService.Application.csproj" />
    <ProjectReference Include="..\..\src\OrderService.Domain\OrderService.Domain.csproj" />
    <ProjectReference Include="..\..\src\OrderService.Infrastructure\OrderService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>